CREATE TABLE IF NOT EXISTS APP_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    FNAME VARCHAR(255),
    AGE INT
);

INSERT INTO APP_USER (USERNAME, PASSWORD, FNAME, AGE) VALUES ('chaunm', '12345', 'Nguyen Minh Chau', 23);